### ISSUE TITLE
Remove Q1 and Q2 fields.

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/sacc#10]
With type being upgraded to two letter thing, perhaps it is time to retire Q1 and Q2. 
The reader should gracefully deal with files that do have these quantities.

**Comment by damonge** [comment]
@slosar I'm all for this.
However, in line with this: could we upgrade the "type" to a >=4 letter thing? That way we could have `ClEE`, `ClEB`, `ClBE`, `ClBB`, `XiP` etc.

If we wanna keep 2 letters, I guess it would be possible, but one would have to understand that e.g. `EE` implies Fourier-space measurements too. Currently TJPcosmo just uses `FF` for Fourier-space measurements, but that's because it assumes that all power spectra are just E-modes. This is clearly not good enough, I think.

**Comment by slosar** [comment]
Let's do whatever is least likely to lead to confusion. 
Any number of letters fine, but also give examples for all possible combinations and make sure we use the same thing for the same quantity. Say I have a galaxy sample for which I have both shears measurments and galaxy density measurments. How do I denote cross-correlations between this and CMB kappa?
Also, can we encode things like kSZ? I guess one thing that we cannot do is spectroscopic power spectra, right?

**Comment by damonge** [comment]
But do we need to specify anything about the actual physical object we're correlating here in `type`? I'd say the only thing `type` needs to convey is the geometrical properties of the correlation, such as whether it's EE, BB etc. whether it's Fourier or real-space... The physical properties should be defined by the two tracers that contribute to that cross-correlation (and that's how you'd distinguish whether things are kappa or delta_g or T or kSZ or whatever).

Not sure why we couldn't have P(k) (the type for this one could be `Pk` or something like that)

**Comment by slosar** [comment]
But this is then an important question. If I have a sample of z=1.0+-0.1 galaxies and I have both shears for them and also use them as point tracer, do I have two independent "tracer" objects then (with duplicate N(z), etc) or not? THe idea was not, but perhaps you're right that it might be easier to just duplicate.

**Comment by damonge** [comment]
Oh, I see. I assumed a "tracer" is essentially an independent sky map, so those would be two independent tracers indeed. If replicating N(z)s is a worry, we can think of a workaround, but I think

a) The occasions when this will happen are not so frequent, since you usually select different samples for clustering and lensing.
b) If the worry if storage efficiency, I'd imagine most of the space will be taken up by the covariance matrix, so this is an epsilon.

**Comment by damonge** [comment]
(Note that this is also the interpretation of what a Tracer/Source/NmtField is in CCL/TJPCosmo/NaMaster

**Comment by joezuntz** [comment]
This is now superseded by the new format version 0.2
