### ISSUE TITLE
concatenation of files

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/sacc#41]
I’d be nice to have a method to concatenate files together.

**Comment by joezuntz** [comment]
A few notes mainly to myself on this.

- Combining the data points is trivial, just concatenate the python lists

- Combining the covariances is straightforward - we can create a BlockDiagonalCovariance from the pieces.  That wastes quite a bit of space if one of the components is a DiagonalCovariance.  This could be fixed by upgrading BlockDiagonal so that some of the blocks can be diagonal instead of full (punt this for now).  Either all the concatenated data sets should have covariances or none of them should.

- Combining sets of tracers is okay.  If two have the same name (but are not identical) then we could 1) rename one or both of them with a suffix,  2) raise an error.  3) Or control this using options.

- Metadata is probably the fiddliest bit - choices I can see are: 1) add a suffix to all keys, 2) add a suffix to all keys present in both, 3) add a suffix to all keys with clashing values, 4) allow one to override the other, 5) pick a strategy using a keyword choice.  I think that's how astropy tables handle this, but might be over-complicated.
